-- Schema for auth_db
CREATE DATABASE IF NOT EXISTS pfe_bd DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pfe_bd;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
